FROM node:20
WORKDIR /app
COPY package*.json ./
RUN npm install
# RUN npm install bcrypt
COPY . .
EXPOSE 5005 
EXPOSE 5000
# CMD ["sh", "-c", "npm run dev & npm run chat && wait"]
CMD ["npm", "run", "dev"]
